version: "3.8"
services:
  db:
    container_name: project-manager
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_USER: "root"
      MYSQL_ROOT_PASSWORD: "password"
    networks:
      - project-manager

networks:
  project-manager:
